name: Send Daily Protein Reminders
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        run: curl -d "Log your protein today!" https://ntfy.sh/pt-53v5g6mt-h$(date -u +%-H)
